
export const FETCH_SEARCH = 'FETCH_SEARCH'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'

export const CREATE_HISTORY = 'CREATE_HISTORY'
export const FETCH_HISTORY = 'FETCH_HISTORY'
export const UPDATE_HISTORY = 'UPDATE_HISTORY'
export const SONG_SELECTED = 'SONG_SELECTED'
export const ADD_TO_QUEUE = 'ADD_TO_QUEUE'
export const REMOVE_FROM_QUEUE = 'REMOVE_FROM_QUEUE'
export const CLEAR_HISTORY = 'CLEAR_HISTORY'

export const PLAYLIST_SELECTED = 'PLAYLIST_SELECTED'
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST'
export const FETCH_ALL_PLAYLISTS = 'FETCH_ALL_PLAYLISTS'
export const UPDATE_PLAYLIST_SONGS = 'UPDATE_PLAYLIST_SONGS'
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST'
export const CLEAR_PLAYLIST = 'CLEAR_PLAYLIST'


export const CREATE_USER = 'CREATE_USER'
export const LOGGED_IN = 'LOGGED_IN'
export const DUPLICATE_EMAIL = 'DUPLICATE_EMAIL'
export const CLEAR_INPUT = 'CLEAR_INPUT'
export const LOGIN = 'LOGIN'
export const LOG_OUT = 'LOG_OUT'