

export const UPDATE_HISTORY = 'UPDATE_HISTORY'
export const SONG_SELECTED = 'SONG_SELECTED'
export const SEARCH_SONG = 'SEARCH_SONG'
export const ADD_PLAYLIST = 'ADD_PLAYLIST'
export const ADD_TO_QUEUE = 'ADD_TO_QUEUE'
export const REMOVE_FROM_QUEUE = 'REMOVE_FROM_QUEUE'
export const PLAYLIST_SELECTED = 'PLAYLIST_SELECTED'
export const UPDATE_PLAYLIST_SONGS = 'UPDATE_PLAYLIST_SONGS'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'


export const CREATE_PLAYLIST = 'CREATE_PLAYLIST'
export const FETCH_ALL_PLAYLISTS = 'FETCH_ALL_PLAYLISTS'


